export * from "./Base.ts";
export * from "./UniversityButtonInteraction.ts"
export * from "./UniversityChannel.ts";
export * from "./UniversityGuild.ts";
export * from "./UniversityMember.ts";
export * from "./UniversityMessage.ts";
export * from "./UniversityRole.ts";
export * from "./UniversitySlashInteraction.ts"
export * from "./UniversityVoiceState.ts";
